# Generated by Django 4.2.4 on 2023-08-22 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitecode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='gst',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='service',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sitecode.client'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='AddClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp2_name', models.CharField(max_length=50)),
                ('handle_by', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('account', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=20)),
                ('bank', models.CharField(max_length=40)),
                ('gst', models.CharField(max_length=15)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sitecode.client')),
            ],
        ),
    ]
