# Generated by Django 4.2.4 on 2023-08-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitecode', '0002_alter_client_gst_alter_service_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addclient',
            table='providers',
        ),
    ]
